-- Favorites feature. Run once in the Supabase SQL Editor. Safe to re-run.

CREATE TABLE IF NOT EXISTS public.favorite_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Defaults to the caller, so the client never sends (or spoofs) a user id.
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    -- Shared identity of a place across users: 'osm:<type>:<id>' or 'geo:<lat>:<lon>:<slug>'.
    -- Must match favorites/keys.py make_place_key() and static/js/favorites.js placeKey().
    place_key TEXT NOT NULL CHECK (char_length(place_key) <= 128),
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
    category TEXT NOT NULL DEFAULT '' CHECK (char_length(category) <= 60),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    address TEXT NOT NULL DEFAULT '' CHECK (char_length(address) <= 255),
    potential_score SMALLINT CHECK (potential_score BETWEEN 0 AND 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, place_key)
);

CREATE INDEX IF NOT EXISTS favorite_places_place_key_idx ON public.favorite_places (place_key);
CREATE INDEX IF NOT EXISTS favorite_places_created_at_idx ON public.favorite_places (created_at DESC);

-- Row Level Security: each user sees and changes only their own rows.
ALTER TABLE public.favorite_places ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own favorites" ON public.favorite_places;
CREATE POLICY "Users read own favorites" ON public.favorite_places
    FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Insert is also capped at 500 favorites per user.
DROP POLICY IF EXISTS "Users add own favorites" ON public.favorite_places;
CREATE POLICY "Users add own favorites" ON public.favorite_places
    FOR INSERT TO authenticated WITH CHECK (
        auth.uid() = user_id
        AND (SELECT count(*) FROM public.favorite_places f WHERE f.user_id = auth.uid()) < 500
    );

DROP POLICY IF EXISTS "Users delete own favorites" ON public.favorite_places;
CREATE POLICY "Users delete own favorites" ON public.favorite_places
    FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Community feed for the recommender. RLS hides other users' rows, so this
-- SECURITY DEFINER function returns recent favorites from everyone WITHOUT
-- user_id. Each row is still one distinct saver of that place, because of
-- UNIQUE (user_id, place_key).
CREATE OR REPLACE FUNCTION public.community_favorites(max_rows INT DEFAULT 5000)
RETURNS TABLE (
    place_key TEXT, name TEXT, category TEXT, latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION, address TEXT, potential_score SMALLINT,
    created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT place_key, name, category, latitude, longitude, address, potential_score, created_at
    FROM public.favorite_places
    ORDER BY created_at DESC
    LIMIT LEAST(GREATEST(max_rows, 1), 5000);
$$;

REVOKE ALL ON FUNCTION public.community_favorites(INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.community_favorites(INT) TO authenticated;
