-- User history: lets a signed-in user see and revisit their past searches,
-- analyses, feasibility checks and startup inquiries.
-- Run once in the Supabase SQL Editor (after the original schema). Safe to re-run.

-- 1. One timeline table for every kind of past action ----------------------
CREATE TABLE IF NOT EXISTS public.user_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Defaults to the caller; clients cannot set it (see column grants below).
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN (
        'search',               -- /search-location/
        'crowd_analysis',       -- /analyze-crowd-intensity/ (heatmap)
        'popular_places_scan',  -- /find-popular-places/
        'location_analysis',    -- /api/analyze-location/ (revenue intelligence)
        'best_locations',       -- /api/generate-best-locations/ (AI zones)
        'feasibility_check',    -- /check-feasibility/
        'startup_inquiry'       -- /submit-form/ (startup form)
    )),
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
    location_name TEXT NOT NULL DEFAULT '' CHECK (char_length(location_name) <= 255),
    latitude DOUBLE PRECISION CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION CHECK (longitude BETWEEN -180 AND 180),
    business_type TEXT NOT NULL DEFAULT '' CHECK (char_length(business_type) <= 100),
    -- Key results only (e.g. feasible, dominant_intensity, potential_score,
    -- estimated_monthly_revenue), not the full API response.
    summary JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(summary) = 'object' AND pg_column_size(summary) <= 16384),
    -- Pinned entries are kept forever and never trimmed.
    pinned BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE INDEX IF NOT EXISTS user_history_user_created_idx ON public.user_history (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS user_history_user_kind_idx ON public.user_history (user_id, kind, created_at DESC);

-- 2. Row Level Security: a user only ever sees their own history ------------
ALTER TABLE public.user_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own history" ON public.user_history;
CREATE POLICY "Users read own history" ON public.user_history
    FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users add own history" ON public.user_history;
CREATE POLICY "Users add own history" ON public.user_history
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users pin own history" ON public.user_history;
CREATE POLICY "Users pin own history" ON public.user_history
    FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete own history" ON public.user_history;
CREATE POLICY "Users delete own history" ON public.user_history
    FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Column-level grants: Supabase grants everything to anon/authenticated by
-- default. Narrow that so clients can't backdate created_at, set user_id, or
-- edit an entry after the fact (only pin/unpin it).
REVOKE ALL ON public.user_history FROM anon, authenticated;
GRANT SELECT, DELETE ON public.user_history TO authenticated;
GRANT INSERT (kind, title, location_name, latitude, longitude, business_type, summary, pinned)
    ON public.user_history TO authenticated;
GRANT UPDATE (pinned) ON public.user_history TO authenticated;

-- 3. "Last active" on the profile ---------------------------------------------
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMP WITH TIME ZONE;

-- 4. After each insert: refresh last_seen_at and keep at most 1000 unpinned
--    entries per user (oldest are dropped).
CREATE OR REPLACE FUNCTION public.after_user_history_insert()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    UPDATE public.profiles
       SET last_seen_at = NEW.created_at
     WHERE id = NEW.user_id
       AND (last_seen_at IS NULL OR last_seen_at < NEW.created_at - interval '5 minutes');

    DELETE FROM public.user_history
     WHERE id IN (
        SELECT id FROM public.user_history
         WHERE user_id = NEW.user_id AND NOT pinned
         ORDER BY created_at DESC
        OFFSET 1000
     );
    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.after_user_history_insert() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS on_user_history_insert ON public.user_history;
CREATE TRIGGER on_user_history_insert
    AFTER INSERT ON public.user_history
    FOR EACH ROW EXECUTE FUNCTION public.after_user_history_insert();

-- 5. Read-only views for the "My History" page --------------------------------
-- security_invoker = true makes the views run with the caller's permissions,
-- so the RLS policies above still apply (views otherwise bypass RLS).

-- Counts and last use per feature, e.g. "12 feasibility checks, last 2 days ago".
CREATE OR REPLACE VIEW public.my_history_summary WITH (security_invoker = true) AS
SELECT kind,
       count(*)        AS total,
       max(created_at) AS last_used
  FROM public.user_history
 WHERE user_id = auth.uid()
 GROUP BY kind;

-- Distinct places the user has looked at (~100 m grid), newest action per place.
CREATE OR REPLACE VIEW public.my_recent_places WITH (security_invoker = true) AS
SELECT DISTINCT ON (round(latitude::numeric, 3), round(longitude::numeric, 3))
       location_name,
       latitude,
       longitude,
       kind       AS last_action,
       title      AS last_title,
       created_at AS last_visited
  FROM public.user_history
 WHERE user_id = auth.uid() AND latitude IS NOT NULL
 ORDER BY round(latitude::numeric, 3), round(longitude::numeric, 3), created_at DESC;

REVOKE ALL ON public.my_history_summary, public.my_recent_places FROM anon, authenticated;
GRANT SELECT ON public.my_history_summary, public.my_recent_places TO authenticated;
