# Generated by Django 6.0 on 2026-08-24
from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    """
    Ensure existing users in the database prior to the email verification system
    are marked as verified so they are not inadvertently locked out.
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether this user has verified their email address.',
                verbose_name='email verified',
            ),
        ),
        migrations.RunPython(
            mark_existing_users_verified,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
