# Generated by Django 6.0.7 on 2026-08-24 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password update.', null=True, verbose_name='password last changed'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Secondary email address for account recovery.', max_length=254, null=True, verbose_name='recovery email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 encoded secret key for TOTP 2FA.', max_length=64, null=True, verbose_name='TOTP secret'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether two-factor authentication is active.', verbose_name='2FA enabled'),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Successful Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset Completed'), ('EMAIL_VERIFIED', 'Email Address Verified'), ('2FA_ENABLED', 'Two-Factor Authentication Enabled'), ('2FA_DISABLED', 'Two-Factor Authentication Disabled'), ('RECOVERY_CODE_USED', '2FA Recovery Code Used'), ('RECOVERY_CODES_REGENERATED', '2FA Recovery Codes Regenerated'), ('FAILED_2FA_ATTEMPT', 'Failed 2FA Attempt'), ('ACCOUNT_RECOVERY', 'Account Recovery Initiated'), ('ALL_SESSIONS_REVOKED', 'All Other Sessions Revoked')], max_length=50, verbose_name='event type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Hashed representation of the recovery code.', max_length=128, verbose_name='code hash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA recovery code',
                'verbose_name_plural': '2FA recovery codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user agent')),
                ('device_name', models.CharField(default='Web Browser', max_length=100, verbose_name='device name')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'active session',
                'verbose_name_plural': 'active sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
