# Generated by Django 6.0.7 on 2026-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_security_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Unique identifier from Supabase auth.users', null=True, unique=True, verbose_name='Supabase Auth User ID'),
        ),
    ]
