# Generated by Django 6.0.7 on 2026-07-16 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_webhook_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep', models.CharField(max_length=100)),
                ('energy', models.PositiveIntegerField(default=5)),
                ('mood', models.PositiveIntegerField(default=5)),
                ('main_mission', models.CharField(max_length=255)),
                ('definition_of_done', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('wins', models.TextField(blank=True)),
                ('avoidance', models.TextField(blank=True)),
                ('distractions', models.TextField(blank=True)),
                ('daydreaming_occurred', models.BooleanField(default=False)),
                ('daydreaming_trigger', models.CharField(blank=True, max_length=255)),
                ('daydreaming_duration', models.CharField(blank=True, max_length=100)),
                ('daydreaming_preceded_by', models.TextField(blank=True)),
                ('daydreaming_interrupted_by', models.TextField(blank=True)),
                ('xp_body', models.PositiveIntegerField(default=0)),
                ('xp_knowledge', models.PositiveIntegerField(default=0)),
                ('xp_communication', models.PositiveIntegerField(default=0)),
                ('xp_discipline', models.PositiveIntegerField(default=0)),
                ('xp_reflection', models.PositiveIntegerField(default=0)),
                ('starting_easy', models.TextField(blank=True)),
                ('starting_difficult', models.TextField(blank=True)),
                ('tomorrow_mission', models.CharField(blank=True, max_length=255)),
                ('tomorrow_action', models.CharField(blank=True, max_length=255)),
                ('reward', models.CharField(blank=True, max_length=255)),
                ('coach_score', models.CharField(default='Bronze', max_length=50)),
                ('coach_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
