# Generated by Django 6.0.7 on 2026-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='reflection_answer',
            field=models.TextField(blank=True),
        ),
    ]
