import json
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

SUPABASE_CREATE_TABLE_SQL = """
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/ijsfmdgysmwovaighumv/sql)
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id TEXT,
    user_email TEXT,
    event_type TEXT NOT NULL,
    feature_name TEXT,
    details JSONB DEFAULT '{}'::jsonb,
    ip_address TEXT
);

-- Enable RLS and allow insert / select
ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon insert" ON public.user_activity_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow select" ON public.user_activity_logs FOR SELECT USING (true);
"""

_supabase_client = None


def get_supabase_client():
    global _supabase_client
    if _supabase_client is not None:
        return _supabase_client

    try:
        from supabase import create_client
        url = getattr(settings, 'SUPABASE_URL', 'https://ijsfmdgysmwovaighumv.supabase.co')
        key = getattr(settings, 'SUPABASE_ANON_KEY', 'sb_publishable_EdW1JxXZSkEA1uV4Yl4eIg_F9dvq-2h')
        _supabase_client = create_client(url, key)
        return _supabase_client
    except Exception as e:
        logger.warning(f"Could not initialize Supabase client: {e}")
        return None


def log_activity_to_supabase(event_type, feature_name=None, user_id=None, user_email=None, details=None, ip_address=None):
    """
    Inserts an activity log into the Supabase user_activity_logs table.
    Fails gracefully if the table is not yet created.
    """
    client = get_supabase_client()
    if not client:
        return {'success': False, 'message': 'Supabase client not initialized'}

    payload = {
        'event_type': str(event_type),
        'feature_name': str(feature_name) if feature_name else '',
        'user_id': str(user_id) if user_id else None,
        'user_email': str(user_email) if user_email else None,
        'details': details if isinstance(details, (dict, list)) else {'info': str(details or '')},
        'ip_address': str(ip_address) if ip_address else None,
    }

    try:
        response = client.table('user_activity_logs').insert(payload).execute()
        return {'success': True, 'data': response.data if hasattr(response, 'data') else None}
    except Exception as e:
        err_msg = str(e)
        logger.warning(f"Supabase logging warning: {err_msg}")
        return {'success': False, 'error': err_msg, 'table_needed_sql': SUPABASE_CREATE_TABLE_SQL}
