# Generated by Django 6.0.7 on 2026-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(max_length=100)),
                ('recommended_business', models.CharField(blank=True, max_length=100, null=True)),
                ('crowd_intensity', models.CharField(choices=[('high', 'High - High intensity crowded area'), ('medium', 'Medium - Moderate crowd intensity'), ('low', 'Low - Low crowd intensity')], max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
